In [22]:
import pandas as pd
import numpy as np

In [41]:
raw = pd.read_csv("modbus audax.txt",header=None)
raw.head(30)

                                                    0
0                             [21/12/2017 11:12:48]\t
1                            Modbus Response (COM4)\t
2                                        Address: 1\t
3    Function: 16 (0x10) - Write Multiple Registers\t
4                             Starting Address: 182\t
5                                      Quantity: 44\t
6                              Checksum: 20732(BAD)\t
7   ----------------------------------------------...
8                             [21/12/2017 11:12:48]\t
9                            Modbus Response (COM4)\t
10                                      Address: 25\t
11                               Function: 0 (0x00)\t
12                             Checksum: 15155(BAD)\t
13  ----------------------------------------------...
14                            [21/12/2017 11:12:49]\t
15                           Modbus Response (COM4)\t
16                                       Address: 1\t
17      Function: 3 (0x03) - Read Holding Registers\t
18                                    Byte Count: 1\t
19                                      Values: 2b \t
20                              Checksum: 30154(OK)\t
21  ----------------------------------------------...
22                            [21/12/2017 11:12:51]\t
23                           Modbus Response (COM4)\t
24                                       Address: 1\t
25   Function: 16 (0x10) - Write Multiple Registers\t
26                             Starting Address: 99\t
27                                     Quantity: 83\t
28                              Checksum: 53002(OK)\t
29  ----------------------------------------------...

In [45]:
raw.columns = ['Messy']

In [46]:
raw.head()

                                              Messy
0                           [21/12/2017 11:12:48]\t
1                          Modbus Response (COM4)\t
2                                      Address: 1\t
3  Function: 16 (0x10) - Write Multiple Registers\t
4                           Starting Address: 182\t

In [47]:
df = pd.DataFrame()

In [50]:
#check separator
sep_col = raw['Messy'].str.startswith('----')  #.str

In [51]:
#create groups
raw['groups'] = sep_col.cumsum() #this is the key!!!

In [52]:
#filter separator rows
df = raw[~sep_col].copy()   #.copy()
# count ranking in each group
df['ranks'] = df.groupby('groups').cumcount()
df.head(30)

                                               Messy  groups  ranks
0                            [21/12/2017 11:12:48]\t       0      0
1                           Modbus Response (COM4)\t       0      1
2                                       Address: 1\t       0      2
3   Function: 16 (0x10) - Write Multiple Registers\t       0      3
4                            Starting Address: 182\t       0      4
5                                     Quantity: 44\t       0      5
6                             Checksum: 20732(BAD)\t       0      6
8                            [21/12/2017 11:12:48]\t       1      0
9                           Modbus Response (COM4)\t       1      1
10                                     Address: 25\t       1      2
11                              Function: 0 (0x00)\t       1      3
12                            Checksum: 15155(BAD)\t       1      4
14                           [21/12/2017 11:12:49]\t       2      0
15                          Modbus Response (COM4)\t       2      1
16                                      Address: 1\t       2      2
17     Function: 3 (0x03) - Read Holding Registers\t       2      3
18                                   Byte Count: 1\t       2      4
19                                     Values: 2b \t       2      5
20                             Checksum: 30154(OK)\t       2      6
22                           [21/12/2017 11:12:51]\t       3      0
23                          Modbus Response (COM4)\t       3      1
24                                      Address: 1\t       3      2
25  Function: 16 (0x10) - Write Multiple Registers\t       3      3
26                            Starting Address: 99\t       3      4
27                                    Quantity: 83\t       3      5
28                             Checksum: 53002(OK)\t       3      6
30                           [21/12/2017 11:12:53]\t       4      0
31                          Modbus Response (COM4)\t       4      1
32                                      Address: 1\t       4      2
33  Function: 16 (0x10) - Write Multiple Registers\t       4      3

In [54]:
df_new = df.pivot('groups','ranks','Messy')

In [57]:
df_new

(245, 85)

In [58]:
df_new.to_csv("Cleaned_records.csv")